# Test Dirichlet BCs

In [6]:
include("fem.jl")

apply_dirichlet_bcs! (generic function with 2 methods)

Test data

In [7]:
N = 5
K = collect(reshape(1:N^2, N, N))
r = collect(1:N);

Vorher

In [8]:
display(K)
display(r)

5×5 Matrix{Int64}:
 1   6  11  16  21
 2   7  12  17  22
 3   8  13  18  23
 4   9  14  19  24
 5  10  15  20  25

5-element Vector{Int64}:
 1
 2
 3
 4
 5

Nachher

In [9]:
apply_dirichlet_bcs!(K, r, [1, 3])
display(K)
display(r)

5×5 Matrix{Int64}:
 1   0   0   0   0
 2   7  12  17  22
 0   0   1   0   0
 4   9  14  19  24
 5  10  15  20  25

5-element Vector{Int64}:
 0
 2
 0
 4
 5